### PR TITLE
Explore page

### PR DESCRIPTION
**Pull request by nikhiljugale007**
PREVIEW: https://deploy-preview-2--awesome-newton-2f99fb.netlify.app/pages/explore.html

Added explore page: 
Contains the title of the category, category description. 
Then all quizzes are listed in that category in the form of cards.
s1
s2

### CODE REVIEW

**Comment by Sahil25061999** [comment]
The cards in the second row are not working.

**Comment by Naman-Saxena1** [comment]
A UI suggestion, you can add some dark background color to "Take Quiz" on hover so it does not merge with below image.

**Comment by nikhiljugale007** [comment]
> The cards in the second row are not working.

That because of the small netlify footer, if you close that it works. 
Can you check by closing that netlify footer which appear at the bottom.

**Comment by nikhiljugale007** [comment]
> A UI suggestion, you can add some dark background color to "Take Quiz" on hover so it does not merge with below image.

implemented your suggestion in latest commit.

**Pull request merged**
